"""empty message

Revision ID: 31116634d928
Revises: 2d68edd689b9
Create Date: 2026-10-05 11:12:46.608429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31116634d928'
down_revision = '2d68edd689b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('guid'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('guid'), ['guid'])

    # ### end Alembic commands ###
