"""empty message

Revision ID: 572afa34ab49
Revises: 7f3a2c1d9b8e
Create Date: 2026-10-01 09:33:48.810174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '572afa34ab49'
down_revision = '7f3a2c1d9b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_caller_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_caller_cache_process_identifier'))

    op.drop_table('process_caller_cache')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_caller_cache',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('process_identifier', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('calling_process_identifier', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('process_caller_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_caller_cache_process_identifier'), ['process_identifier'], unique=False)

    # ### end Alembic commands ###
