# Only put bootstrap users in here
# Other users should be defined via DMN or IDP groups

users:
  admin:
    service: local_open_id
    email: admin@example.com
    password: admin
    preferred_username: admin
  adminX:
    service: bootstrap

groups:
  admin:
    users: [admin@example.com, adminX@bootstrap]

permissions:
  # Admins have access to everything.
  admin:
    groups: [admin]
    actions: [all]
    uri: /*
