name: run_ci

on:
  workflow_dispatch:
  push:
    branches: ['feature/releases'] # just for testing for a bit.
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE: spiffworkflow-backend

jobs:
  build-and-push-backend-container:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/app

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
