name: Frontend Docker

on:
  push:
    branches:
      - feature/create_containers
defaults:
  run:
    working-directory: spiffworkflow-frontend

jobs:
  build-and-push-image:
    if: ${{ github.ref_name == 'main' && github.event_name == 'push' }}
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: sartography/spiffworkflow-frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.0.2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting in sonarcloud
          fetch-depth: 0
      - name: Get current date
        id: date
        run: echo "date=$(date +%s)" >> $GITHUB_OUTPUT
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        env:
          # if we ever support more than main we will need to format the ref name
          # like sub '/' with '-'
          TAG: ${{ github.ref_name }}-${{ steps.date.outputs.date }}
        with:
          # this action doesn't seem to respect working-directory so set context
          context: spiffworkflow-backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}
