name: Slack Notification

on:
  workflow_run:
    workflows: ["Backend Tests"]
    types: [completed]

jobs:
  send_notification:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Workflow <${{ github.event.workflow_run.html_url }}|${{ github.event.workflow.name }}> failed!"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
